### ISSUE TITLE
Will you release the yolopose version?

### ISSUE THREAD

**Issue by DavidJimenezS** [sh-aidev/deepstream-yolo11#1]
Have you thought about adding support for the pose version of yolov11?
Here [DeepStream-Yolo-Pose](https://github.com/marcoslucianops/DeepStream-Yolo-Pose) is the version of yolov8 based on Marcos's project, maybe with that will be easy to move into the pose for yolov11.

**Comment by sh-aidev** [comment]
Hey @DavidJimenezS sure will shortly update.

**Comment by DavidJimenezS** [comment]
Awesome. thanks for your reply.

I'll keep an eye on it.
